Update ImmuSeeker

diff --git a/ImmuSeeker b/ImmuSeeker
--- a/ImmuSeeker
+++ b/ImmuSeeker
@@ -10,16 +10,16 @@
 #######################################Help#########################################
 
 display_help() {
-  echo "Usage: ImmuSeeker [-HLA | -KIR] [-SwithB | -SwithF] -i <Parameter1> -v <Parameter2> -c <Parameter3> -n <Parameter4>  -p <Parameter5> -p1 <Parameter6> -o <Parameter7>  -er <Parameter8> -ex <Parameter9> -pt <Parameter10> -dv <Parameter11> -nr <Parameter12>"
+  echo "Usage: ImmuSeeker [-HLA | -KIR] [-SwithB | -SwithF | -Update] -i <Parameter1> -v <Parameter2> -c <Parameter3> -n <Parameter4>  -p <Parameter5> -p1 <Parameter6> -o <Parameter7>  -er <Parameter8> -ex <Parameter9> -pt <Parameter10> -dv <Parameter11> -nr <Parameter12>"
   echo "Options:"
   echo "  -HLA     Invoke the HLA calling process."
   echo "  -KIR     Invoke the KIR calling process."
   echo "  -SwithB  Input alignment BAM file."
   echo "  -SwithF  Input FASTQ file."
-  echo "  -i       Set the input directory and filename. Example: 'your/input/directory/inputfile.bam'."
-  echo "  -v       Input parameter or file name. 
-	   If using -SwithB, specify the genome version with '-v hg37' or '-v hg38'. 
+  echo "  -Update  Update to latest IMGT-HLA/KIR version."
+  echo "  -i       Set the input directory and filename. Example: 'your/input/directory/inputfile.bam'.
 	   If using -SwithF, specify FASTQ file(s) with '-i file1,file2' (two files) or '-i file' (one file)."
+  echo "  -v       If using -SwithB, specify the genome version with '-v hg37' or '-v hg38'. "
   echo "  -c       Specify min number of supported unique reads (default: 5)."  
   echo "  -n       Max mismatches in seed (default: 0)."
   echo "  -p       Set a noninformative flat prior to allow the data to have a strong influence on the posterior distribution. (default: -p '(1/3,1/3,1/3)')."
@@ -40,6 +40,7 @@ HLA="false"
 KIR="false"
 swithB="false"
 swithF="false"
+update_v="false"
 param_ex="false"
 param_pt="false"
 param_dv="false"
@@ -52,6 +53,7 @@ param_p="(1/3,1/3,1/3)"
 param_p1=0.5
 param_n=0
 param_nr="HLAn"
+
 
 
 #######################################Process command line options#######################
@@ -69,6 +71,9 @@ while [[ "$#" -gt 0 ]]; do
       ;;
     -SwithF)
       swithF="true"
+      ;;
+	-Update)
+      update_v="true"
       ;;
     -i)
       param_i="$2" #"/ImmuSeeker_data/$2"
@@ -129,6 +134,7 @@ while [[ "$#" -gt 0 ]]; do
   shift
 done
 
+
 # Validate options
 if [[ ($HLA != "true" && $KIR != "true") || ($HLA == "true" && $KIR == "true") ]]; then
   echo "Error: Please provide either -HLA or -KIR"
@@ -136,23 +142,39 @@ if [[ ($HLA != "true" && $KIR != "true") || ($HLA == "true" && $KIR == "true") ]
 fi
 
 
-if [[ ($swithB != "true" && $swithF != "true")  || ($swithB == "true" && $swithF == "true")  ]]; then
-  echo "Error: Please provide either -SwithB or -SwithF."
+if [[ ($swithB != "true" && $swithF != "true" && $update_v != "true")  || ($swithB == "true" && $swithF == "true" && $update_v == "true")  ]]; then
+  echo "Error: Please provide either -SwithB, -SwithF or -Update."
   display_help
 fi
 
 
 
-if [[ -z $param_i ]]; then
+if [[ ($update_v != "true" && -z $param_i) ]]; then
   echo "Error: Please Ensure that both -i options are included."
   display_help
+else
+	if echo "$param_i" | grep -q ','; then
+		result=$(echo "$param_i" | tr -d ' ' | tr ',' '\n')
+		f1="$(echo "$result" | awk 'NR==1 {print}')"&&
+		f22="$(echo "$result" | awk 'NR==2 {print}')"&&
+		f2="$f22"&&#"/ImmuSeeker_data/$f22"
+		param_i="${f1},${f2}"	
+	fi  
+fi
+	
+	
+	
+if [[ ($update_v != "true" && -z $param_o) ]]; then
+	if echo "$param_i" | grep -q ','; then		
+		param_o="$f1""_output"
+	else
+		param_o="$param_i""_output"
+	fi
+  echo "Warning: The output file name is ${param_i}_output!"
+  
 fi
 
-if [[ -z $param_o ]]; then
-  echo "Warning: The output file name is ${param_i}_output!"
-  param_o="$param_i""_output"
-  #display_help
-fi
+	
 
 if [[ $param_ex == "false" && $param_dv == "dve" ]]; then
 	echo "Warning: Diversity analysis cannot be executed because the gene expression value was not provided. 
@@ -190,29 +212,51 @@ echo "Parameter 12 (-nr): $param_nr"
 #######################################software########################################
 
 
-if [[ "$HLA" == "true" ]]; then
-	echo ".............run HLA.........."
+if [[ "$HLA" == "true" && $update_v != "true" ]]; then
+
+	if [[ "$swithB" == "true" && "$param_i" == *.bam ]]; then
+		echo ".............run HLA.........."
+	elif [[ "$swithF" == "true" && ("$param_i" == *.fq || "$param_i" == *.fastq) ]]; then
+		echo ".............run HLA.........."
+	else
+		echo -e "................Error: Unsupported file type. ................ \n If '-SwithB' is selected, a BAM file with a '.bam' extension is required. \n If '-SwithF' is selected, a FASTQ file with a '.fq' or '.fastq' extension is required."
+		exit 1
+	fi
+
+	# Define parameters only once
 	parameters=(
 		"$swithB"
 		"$swithF"
 		"$param_i"
 		"$param_o"
-		"$param_ex"		
+		"$param_ex"        
 		"$param_v"
 		"$param_er"
-		"$param_c"		
+		"$param_c"        
 		"$param_p"
 		"$param_p1"
 		"$param_n"
 		"$param_pt"
 		"$param_dv"
-		"param_nr"
+		"$param_nr"
 	)
-  . code/HLAdetector "${parameters[@]}"
+
+	# Run HLA detector
+	. code/HLAdetector "${parameters[@]}"
+	
 fi
 
-if [[ "$KIR" == "true" ]]; then
-	echo ".............run KIR.........."
+if [[ "$KIR" == "true" && $update_v != "true" ]]; then
+
+	if [[ "$swithB" == "true" && "$param_i" == *.bam ]]; then
+		echo ".............run KIR.........."
+	elif [[ "$swithF" == "true" && ("$param_i" == *.fq || "$param_i" == *.fastq) ]]; then
+		echo ".............run KIR.........."
+	else
+		echo -e "................Error: Unsupported file type. ................ \n If '-SwithB' is selected, a BAM file with a '.bam' extension is required. \n If '-SwithF' is selected, a FASTQ file with a '.fq' or '.fastq' extension is required."
+		exit 1
+	fi
+	
 	parameters=(
 		"$swithB"
 		"$swithF"
@@ -234,3 +278,17 @@ fi
 
 
 
+if [[ "$HLA" == "true" && $update_v == "true" ]]; then
+	echo "..........update HLA to latest IMGT/HLA version.........."	
+	Rscript  code/update_reference_HLA.R
+	echo "..........index the latest IMGT/HLA fasta.........."	
+	bowtie-build data/hla_nuc.fasta data/hla_nuc
+fi
+
+
+if [[ "$KIR" == "true" && $update_v == "true" ]]; then
+	echo "..........update KIR to latest IMGT/KIR version.........."	
+	Rscript  code/update_reference_KIR.R
+	echo "..........index the latest IMGT/KIR fasta.........."	
+	bowtie-build data/kir_nuc.fasta data/kir_nuc
+fi
